source 'https://rubygems.org' do
  gem 'generamba', '1.4.0'
  gem 'cocoapods', '1.0.1'
  gem 'xcpretty', :git => 'https://github.com/MrCloud/xcpretty.git', :branch => 'fix/duration_of_failed_tests_workaround'
end
