source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/RedP4nda/Specs.git'

platform :ios, '9.0'
use_frameworks!

def redpanda
  pod 'RPFramework', '~> 0.9'
  pod 'SwiftLint'
end

def config
    pod 'Natrium', :git => 'https://github.com/MrCloud/Natrium.git'
end

def logging
    pod 'RPLoggerz', '~> 0.9'
end

def networking
    pod 'RPHTTPServiceClient', '~> 0.9'
    pod 'RPImageLoader/KingFisher', '~> 0.9'
end

def ui
   pod 'IBAnimatable', '4.2.0'
   pod 'Hero', '1.0.0-alpha.4'
   pod 'RPImageLoader/KingFisher'
end

def tests
    pod 'Quick'
    pod 'Nimble'
    pod 'ObjectMapper', '2.2.7'
end

def uitests
    pod 'SnappyTestCase'
end


target 'RedPanda_TEMPLATE' do
  redpanda
  networking
  logging
  config
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
